name: vak
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.6
  - attrs
  - dask
  - joblib
  - numpy
  - pandas
  - pytorch
  - scipy
  - toml
  - torchvision
  - tqdm
  - pip:
    - evfuncs
    - koumura
    - crowsetta>=2.1


