{% set name = "vak" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6047769e2c11a86febe2cf2fab9f82c53be848644c0bb4f9c356d20d5e8060c0

build:
  number: 0
  entry_points:
    - vak=vak.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - attrs >=19.3.*
    - crowsetta ==2.2.0
    - dask >=2.10.*
    - dask-core >=2.10.*
    - joblib >=0.14.1
    - matplotlib >=3.1.3
    - numpy >=1.18.1
    - pip
    - python >=3.6.*
    - pytorch >=1.4.0
    - scipy >=1.4.1
    - toml >= 0.10.0
    - torchvision >=0.5.0
    - tqdm >=4.42.1

  run:
    - attrs >=19.3.*
    - crowsetta ==2.2.0
    - dask >=2.10.*
    - dask-core >=2.10.*
    - joblib >=0.14.1
    - matplotlib >=3.1.3
    - numpy >=1.18.1
    - python >=3.6.*
    - scipy >=1.4.1
    - toml >= 0.10.0
    - torchvision >=0.5.0
    - tqdm >=4.42.1

test:
  imports:
    - vak
    - vak.cli
    - vak.config
    - vak.core
    - vak.core.learncurve
    - vak.io
    - vak.io.dataset
    - vak.io.algorithms
    - vak.plot
    - vak.utils
  commands:
    - vak --help

about:
  home: "https://github.com/NickleDave/vak"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "automated annotation of vocalizations for everybody"
  doc_url: "https://vak.readthedocs.io"
  dev_url: 

extra:
  recipe-maintainers:
    - nickledave
